require('./bootstrap')

import '../css/app.css'
import React from 'react'
import ReactDOM from 'react-dom'
import {library} from '@fortawesome/fontawesome-svg-core'
import {
    fa1,
    faAngleDown,
    faAngleLeft,
    faArrowDown,
    faArrowLeftLong,
    faArrowPointer,
    faArrowRotateLeft,
    faArrowUp,
    faArrowUpFromBracket,
    faArrowUpRightFromSquare,
    faAt,
    faBars,
    faBed,
    faBell,
    faBolt,
    faBook,
    faBookmark,
    faBorderAll,
    faBuilding,
    faBuildingColumns,
    faCalendar,
    faCalendarPlus,
    faCar,
    faCashRegister,
    faChartLine,
    faChartPie,
    faCheck,
    faCheckDouble,
    faChevronDown,
    faCircleQuestion,
    faCity,
    faDatabase,
    faEarthAsia,
    faElevator,
    faEllipsis,
    faEnvelope,
    faEye,
    faFile,
    faFileExcel,
    faFileInvoice,
    faFileLines,
    faFlag,
    faFolderTree,
    faGear,
    faGrip,
    faHandshake,
    faHandshakeAngle,
    faHeading,
    faHeadset,
    faHeart,
    faHouse,
    faHouseLaptop,
    faHouseUser,
    faIdCard,
    faImage,
    faKey,
    faLink,
    faList,
    faLocationDot,
    faLock,
    faMagnifyingGlass,
    faMessage,
    faMoneyBill1Wave,
    faMoneyCheck,
    faMoneyCheckDollar,
    faNewspaper,
    faPaintRoller,
    faPaperclip,
    faParagraph,
    faPause,
    faPenToSquare,
    faPercent,
    faPhone,
    faPhotoFilm,
    faPlay,
    faPlus,
    faPrint,
    faQuestion,
    faRectangleAd,
    faRightFromBracket,
    faRubleSign,
    faS,
    faScrewdriverWrench,
    faSliders,
    faStar,
    faStop,
    faStore,
    faTableList,
    faTrash,
    faTree,
    faUpload,
    faUpRightAndDownLeftFromCenter,
    faUser,
    faUserCheck,
    faUserGear,
    faUserTie,
    faVideo,
    faVolumeHigh,
    faVolumeXmark,
    faWarehouse,
    faXmark
} from '@fortawesome/free-solid-svg-icons'
import {LightgalleryProvider} from 'react-lightgallery'
import {Provider} from 'react-redux'
import {BrowserRouter} from 'react-router-dom'
import {store} from './store/reducers'
import AppRouter from './components/views/AppRouter/AppRouter'

library.add(
    faUser,
    faLock,
    faPhone,
    faAt,
    faBuilding,
    faScrewdriverWrench,
    faBook,
    faFileExcel,
    faGear,
    faBell,
    faMessage,
    faRightFromBracket,
    faAngleLeft,
    faHouse,
    faBolt,
    faPercent,
    faFlag,
    faStar,
    faPlus,
    faUserTie,
    faHeadset,
    faCheck,
    faArrowRotateLeft,
    faUserCheck,
    faHeading,
    faLocationDot,
    faArrowUpRightFromSquare,
    faRubleSign,
    faMagnifyingGlass,
    faAngleDown,
    faEllipsis,
    faCheckDouble,
    faHeart,
    faPenToSquare,
    faPrint,
    faArrowUpFromBracket,
    fa1,
    faUpRightAndDownLeftFromCenter,
    faPaintRoller,
    faElevator,
    faBed,
    faTrash,
    faUpload,
    faTableList,
    faParagraph,
    faQuestion,
    faCircleQuestion,
    faXmark,
    faChevronDown,
    faCity,
    faPaperclip,
    faLink,
    faNewspaper,
    faFileLines,
    faFileInvoice,
    faBuildingColumns,
    faTree,
    faCashRegister,
    faCar,
    faHouseUser,
    faEye,
    faPhotoFilm,
    faImage,
    faVideo,
    faFile,
    faArrowPointer,
    faPlay,
    faPause,
    faVolumeHigh,
    faVolumeXmark,
    faBorderAll,
    faCalendarPlus,
    faDatabase,
    faEnvelope,
    faCalendar,
    faRectangleAd,
    faHandshakeAngle,
    faMoneyBill1Wave,
    faS,
    faKey,
    faList,
    faGrip,
    faIdCard,
    faBars,
    faSliders,
    faBookmark,
    faMoneyCheck,
    faFolderTree,
    faUserGear,
    faEarthAsia,
    faArrowLeftLong,
    faHouseLaptop,
    faArrowUp,
    faArrowDown,
    faChartLine,
    faWarehouse,
    faMoneyCheckDollar,
    faHandshake,
    faStop,
    faChartPie,
    faStore
)

const App = () => {
    return (
        <React.StrictMode>
            <Provider store={store}>
                <LightgalleryProvider lightgallerySettings={{
                    mode: 'lg-fade',
                    cssEasing: 'cubic-bezier(0.25, 0, 0.25, 1)',
                    loop: true,
                    preload: 1,
                    download: false
                }}>
                    <BrowserRouter>
                        <AppRouter/>
                    </BrowserRouter>
                </LightgalleryProvider>
            </Provider>
        </React.StrictMode>
    )
}

if (document.getElementById('root')) {
    ReactDOM.render(<App/>, document.getElementById('root'))
}
