<?php

use App\Http\Controllers\Agent\AgentController;
use App\Http\Controllers\Article\ArticleController;
use App\Http\Controllers\Attachment\AttachmentController;
use App\Http\Controllers\Building\BuildingController;
use App\Http\Controllers\BusinessProcess\BusinessProcessController;
use App\Http\Controllers\Category\CategoryController;
use App\Http\Controllers\Checker\CheckerController;
use App\Http\Controllers\Compilation\CompilationController;
use App\Http\Controllers\Contact\ContactController;
use App\Http\Controllers\Developer\DeveloperController;
use App\Http\Controllers\Document\DocumentController;
use App\Http\Controllers\ExternalUser\ExternalUserController;
use App\Http\Controllers\Feed\FeedController;
use App\Http\Controllers\Mail\MailController;
use App\Http\Controllers\Notification\NotificationController;
use App\Http\Controllers\Partner\PartnerController;
use App\Http\Controllers\Post\PostController;
use App\Http\Controllers\Product\ProductController;
use App\Http\Controllers\Question\QuestionController;
use App\Http\Controllers\Setting\SettingController;
use App\Http\Controllers\Tag\TagController;
use App\Http\Controllers\Tariff\TariffController;
use App\Http\Controllers\Transaction\TransactionController;
use App\Http\Controllers\User\UserController;
use App\Http\Controllers\Widget\WidgetController;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => 'auth:sanctum'], function () {
    Route::apiResource('/agent', AgentController::class);
    Route::apiResource('/article', ArticleController::class);
    Route::apiResource('/attachment', AttachmentController::class);
    Route::apiResource('/building', BuildingController::class);
    Route::apiResource('/business-process', BusinessProcessController::class);
    Route::apiResource('/category', CategoryController::class);
    Route::apiResource('/checker', CheckerController::class);
    Route::apiResource('/compilation', CompilationController::class);
    Route::apiResource('/contact', ContactController::class);
    Route::apiResource('/developer', DeveloperController::class);
    Route::apiResource('/document', DocumentController::class);
    Route::apiResource('/external', ExternalUserController::class);
    Route::apiResource('/feed', FeedController::class);
    Route::apiResource('/mail', MailController::class);
    Route::apiResource('/notification', NotificationController::class);
    Route::apiResource('/partner', PartnerController::class);
    Route::apiResource('/post', PostController::class);
    Route::apiResource('/product', ProductController::class);
    Route::apiResource('/question', QuestionController::class);
    Route::apiResource('/setting', SettingController::class)->only(['index', 'store']);
    Route::apiResource('/tag', TagController::class);
    Route::apiResource('/tariff', TariffController::class)->only(['index', 'show']);
    Route::apiResource('/transaction', TransactionController::class)->only(['index', 'show']);
    Route::apiResource('/user', UserController::class);
    Route::apiResource('/widget', WidgetController::class);
});
